name: Release

on:
  release:
    types: ['published']

permissions:
  contents: write

jobs:
  compile-unixlike:
    name: Compile Unix-Like
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['x86_64-unknown-linux-gnu', 'x86_64-apple-darwin', 'aarch64-apple-darwin']

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1

      - name: Compile ${{ matrix.target }}
        run: |
          deno compile --allow-run --allow-env --allow-read --allow-write --target ${{ matrix.target }} --output release/automkv automkv.ts
          tar -czvf release/${{ matrix.target }}.tar.gz ./release
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          allowUpdates: true
          omitBodyDuringUpdate: true
          
  compile-windows:
    name: Compile Windows
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        
      - name: Compile Windows
        run: |
          deno compile --allow-run --allow-env --allow-read --allow-write --target x86_64-pc-windows-msvc --output release/automkv.exe automkv.ts
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          allowUpdates: true
          omitBodyDuringUpdate: true
